version: '3.3'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0
    ports:
      - '5433:5433'
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    commands: bash -c "
      sudo localedef ru_RU.UTF-8 -i ru_RU -fUTF-8; \
      export LANGUAGE=ru_RU.UTF-8 &&
      export LANG=ru_RU.UTF-8 &&
      export LC_ALL=ru_RU.UTF-8 &&
      sudo locale-gen ru_RU.UTF-8 &&
      sudo dpkg-reconfigure locales &&
      -p 5433 "

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    commands: bash -c "
      python manage.py migrate
      && gunicorn foodgram.wsgi:application --bind 0:8000
      "
    volumes:
      - media_value:/code/media/
      - static_value:/code/static/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  media_value:
  static_value: