# Generated by Django 2.2.16 on 2021-12-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211213_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
