# Generated by Django 2.2.16 on 2022-01-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220103_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecipe',
            old_name='in_shopping_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
