# Generated by Django 2.2.16 on 2022-01-07 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220107_1530'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
    ]
